{% set name = "azure-storage-file-datalake" %}
{% set version = "12.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 89b7556403c29ca5b6531c112f0e2d2ef3f340a9add553e8c3484a25bce6216c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - azure-core <2.0.0,>=1.26.0
    - azure-storage-blob <13.0.0,>=12.16.0b1
    - isodate >=0.6.1
    - typing-extensions >=4.0.1

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.filedatalake

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-file-datalake
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This preview package for Python includes ADLS Gen2 specific API support made available in Storage SDK
  doc_url: https://aka.ms/azsdk-python-storage-filedatalake-ref

extra:
  recipe-maintainers:
    - dhirschfeld
